repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml

- repo: https://github.com/google/go-jsonnet
  rev: v0.20.0
  hooks:
  - id: jsonnet-format
  - id: jsonnet-lint
