repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml

- repo: https://github.com/google/go-jsonnet
  rev: fed90cd9cd733a87f9fb27cfb32a3e08a7695603 # https://github.com/google/go-jsonnet/issues/713
  hooks:
  - id: jsonnet-format
  - id: jsonnet-lint

    # work around https://github.com/google/go-jsonnet/issues/591
    entry: 'parallel jsonnet-lint :::'
