customLanguages:
  jsonnet:
    libraryPath: lib/ast-grep/custom-language/tree-sitter-jsonnet.so
    extensions: [jsonnet]
    expandoChar: _

ruleDirs:
- ./lib/ast-grep/rules

testConfigs:
- testDir: ./lib/ast-grep/rule-tests
