customLanguages:
  jsonnet:
    libraryPath: lib/ast-grep/custom-language/tree-sitter-jsonnet.dylib
    extensions: [jsonnet, libsonnet]
    expandoChar: _

ruleDirs:
- ./lib/ast-grep/rules

utilDirs:
- ./lib/ast-grep/utils
