version: '3'

set: [errexit, nounset, pipefail]

vars:
  BUILD_DIR: build
  SOURCE_DIR: src

env:
  PARALLEL_SHELL: bash
  JSONNET_PATH: lib/jsonnet

includes:
  import: ./lib/tasks/import.yaml
  export: ./lib/tasks/export.yaml

tasks:
  clean:
    vars:
      dirs: |-
        {{.EXPORT_DIR}}
        {{.IMPORT_DIR}}
    cmds:
    - for: { var: dirs, as: dir, split: "\n" }
      cmd: find "{{.dir}}" -depth -mindepth 1 -delete

  open-all:
    prompt: Would you like to re-import built Shortcuts?
    cmds:
    - find build -type f -name "*.shortcut" -execdir open -n -W '{}' \;
