version: '3'

set: [errexit, nounset, pipefail]

env:
  SHORTCUTS_DIR: '{{.HOME}}/Library/Mobile Documents/iCloud~is~workflow~my~workflows/Documents'
  PARALLEL_SHELL: bash

tasks:
  default:
    deps: [import-all]

  import-all:
    cmds:
    - find "$SHORTCUTS_DIR" -type f -name "*.shortcut" -delete
    - shortcuts run 'Export Shortcuts'
    # https://github.com/0xilis/libshortcutsign/blob/main/libshortcutsign.m#L330
    - |
      find "$SHORTCUTS_DIR" -type f -name "*.shortcut" -printf "%P\0" \
      | parallel -0 ' \
          mkdir -p src/{//} \
          && scripts/import "$SHORTCUTS_DIR"/{} > "$(echo src/{.}.jsonnet | tee /dev/stderr)" \
          && rm "$SHORTCUTS_DIR"/{} \
        '

  export-all:
    cmds:
    - |
      find src -type f -name "*.jsonnet" -printf "%P\0" \
      | parallel -0 '
          mkdir -p "${tmpdir:=$(mktemp -d)}"/{//}
          jsonnet src/{} > "$tmpdir"/{.}.json
          plutil -convert xml1 "$tmpdir"/{.}.json -o "$tmpdir"/{.}.wflow
          mkdir -p build/{//}
          shortcuts sign -i "$tmpdir"/{.}.wflow -o build/{.}.shortcut
        '
    - task: open-all

  open-all:
    prompt: Would you like to re-import built Shortcuts?
    cmds:
    - find build -type f -name "*.shortcut" -execdir open -n -W '{}' \;
