version: '3'

set: [errexit, nounset, pipefail]

vars:
  EXPORT_DIR: ./build
  EXPORT_EXT: shortcut
  SOURCE_DIR: ./src

env:
  PARALLEL_SHELL: bash
  JSONNET_PATH: lib/jsonnet

includes:
  import: ./lib/tasks/import.yaml
  export: ./lib/tasks/export.yaml

tasks:
  default:
    deps: [import:all]

  clean:
    vars:
      dirs: |-
        {{.EXPORT_DIR}}
        {{.IMPORT_DIR}}
    cmds:
    - for: { var: dirs, as: dir, split: "\n" }
      cmd: find "{{.dir}}" -depth -mindepth 1 -delete

  import-all:
    deps: [clean]
    cmds:

  export-all:
    deps: [clean]
    cmds:
    - >
      find "{{.SOURCE_DIR}}" -type f -name "*.{{.SOURCE_EXT}}" -printf "%H	%P	{{.EXPORT_DIR|replace "%" "%%"}}	{{.EXPORT_EXT}}\0"
      | parallel -0 --colsep='	' 'echo "exporting: "{2} && mkdir -p {3}/{2//} && scripts/export {1}/{2} > {3}/{2.}.{4}'
    - task: open-all

  open-all:
    prompt: Would you like to re-import built Shortcuts?
    cmds:
    - find build -type f -name "*.shortcut" -execdir open -n -W '{}' \;
