version: '3'

set: [errexit, nounset, pipefail]

vars:
  BUILD_DIR: build
  SOURCE_DIR: src

env:
  PARALLEL_SHELL: bash
  JSONNET_PATH: lib/jsonnet

includes:
  import: ./lib/tasks/import.yaml
  export: ./lib/tasks/export.yaml

tasks:
  clean:
    requires:
      vars: [BUILD_DIR]
    cmds:
    - cmd: find "{{q .BUILD_DIR}}" -depth -mindepth 1 -delete
