version: '3'

set: [errexit, nounset, pipefail]

vars:
  BUILD_DIR: build
  SOURCE_DIR: src
  IMPORT_DIR: '{{.HOME}}/Library/Mobile Documents/iCloud~is~workflow~my~workflows/Documents'

env:
  PARALLEL_SHELL: bash
  JSONNET_PATH: lib/jsonnet

includes:
  import: ./lib/tasks/import.yaml
  export: ./lib/tasks/export.yaml

# for skipping up-to-date tasks
method: timestamp

tasks:
  clean:
    requires:
      vars: [BUILD_DIR]
    cmds:
    - cmd: find "{{q .BUILD_DIR}}" -depth -mindepth 1 -delete
